-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 19:07:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testing` DEFAULT CHARACTER SET utf8 ;
USE `testing` ;

-- -----------------------------------------------------
-- Table `testing`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`roles` (
  `id_role` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `permissions` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `id_role_UNIQUE` (`id_role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`users` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(100) NULL,
  `role_id_role` INT UNSIGNED NOT NULL,
  `is_banned` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_users_role_idx` (`role_id_role` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`role_id_role`)
    REFERENCES `testing`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`matches` (
  `id_match` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id_user` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `max_players` INT UNSIGNED NOT NULL,
  `description` VARCHAR(1000) NULL,
  `date_created` DATETIME NOT NULL,
  `date_starting` DATETIME NOT NULL,
  `date_finished` DATETIME NULL,
  `join_code` VARCHAR(70) NULL,
  `join_password` VARCHAR(255) NULL,
  `image_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_match`),
  UNIQUE INDEX `id_match_UNIQUE` (`id_match` ASC) VISIBLE,
  INDEX `fk_matches_users1_idx` (`owner_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_matches_users1`
    FOREIGN KEY (`owner_id_user`)
    REFERENCES `testing`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`nations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`nations` (
  `tag` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `flag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `flag_UNIQUE` (`flag` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`players_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`players_list` (
  `id_match` INT UNSIGNED NOT NULL,
  `id_user` INT UNSIGNED NOT NULL,
  `desired_nation_tag` VARCHAR(3) NULL,
  `status` VARCHAR(15) NULL,
  INDEX `fk_players_list_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_players_list_matches1_idx` (`id_match` ASC) VISIBLE,
  INDEX `fk_players_list_nations1_idx` (`desired_nation_tag` ASC) VISIBLE,
  CONSTRAINT `fk_players_list_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `testing`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_list_matches1`
    FOREIGN KEY (`id_match`)
    REFERENCES `testing`.`matches` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_list_nations1`
    FOREIGN KEY (`desired_nation_tag`)
    REFERENCES `testing`.`nations` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testing`.`banned_players_from_matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testing`.`banned_players_from_matches` (
  `id_user` INT UNSIGNED NOT NULL,
  `id_match` INT UNSIGNED NOT NULL,
  INDEX `fk_banned_players_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_banned_players_matches1_idx` (`id_match` ASC) VISIBLE,
  CONSTRAINT `fk_banned_players_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `testing`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_banned_players_matches1`
    FOREIGN KEY (`id_match`)
    REFERENCES `testing`.`matches` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `testing`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `testing`;
INSERT INTO `testing`.`roles` (`id_role`, `name`, `permissions`) VALUES (1, 'Super Admin', 50);
INSERT INTO `testing`.`roles` (`id_role`, `name`, `permissions`) VALUES (2, 'Admin', 10);
INSERT INTO `testing`.`roles` (`id_role`, `name`, `permissions`) VALUES (3, 'Moderator', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `testing`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `testing`;
INSERT INTO `testing`.`users` (`id_user`, `username`, `password`, `email`, `first_name`, `last_name`, `role_id_role`, `is_banned`) VALUES (1, 'root', '$2y$10$Sn0ZlxcU5zYnB/yFrGMhS.TVmdrz9H/uG1/ZINZugXeULaE0fEQKa', 'root@example.com', NULL, NULL, 1, 0);
INSERT INTO `testing`.`users` (`id_user`, `username`, `password`, `email`, `first_name`, `last_name`, `role_id_role`, `is_banned`) VALUES (2, 'admin', '$2y$10$qVTKAZtewFqqSPmGfzGSK.U/K5vMRvscMRV2xD./GI7goVwave2PW', 'admin@example.com', NULL, NULL, 2, 0);
INSERT INTO `testing`.`users` (`id_user`, `username`, `password`, `email`, `first_name`, `last_name`, `role_id_role`, `is_banned`) VALUES (3, 'moderator', '$2y$10$shS6s3xPLI.B.ZpbTdOiPuKxghmgx1dZbzW/kBH6rVlKg95WUAe/q', 'moderator@example.com', NULL, NULL, 3, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `testing`.`nations`
-- -----------------------------------------------------
START TRANSACTION;
USE `testing`;
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('GER', 'Německo', 'GER_fascism.png');
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('ENG', 'Spojené království', 'ENG_democratic.png');
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('FRA', 'Francie', 'FRA_democratic.png');
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('SOV', 'Sovětský svaz', 'SOV_communism.png');
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('ITA', 'Itálie', 'ITA_fascism.png');
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('POL', 'Polsko', 'POL_neutrality.png');
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('CZE', 'Československo', 'CZE_democratic.png');
INSERT INTO `testing`.`nations` (`tag`, `name`, `flag`) VALUES ('OTH', 'Jiný národ', 'OTH.png');

COMMIT;

